services:
  - type: web
    name: emotion-detection-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "80"
      - key: PYTHON_VERSION
        value: "3.8.10"
    healthCheckPath: /
