services:
  - type: web
    name: emotion-detection-api
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd backend/src && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PIP_VERSION
        value: 23.3.1
    healthCheckPath: /
