services:
  - type: web
    name: emotion-detection-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip==23.3.1 setuptools==68.0.0 wheel==0.40.0
      pip cache purge
      pip install -r requirements.txt --no-cache-dir
    startCommand: cd backend/src && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PIP_VERSION
        value: 23.3.1
      - key: PYTHONPATH
        value: /opt/render/project
    healthCheckPath: /
