services:
  - type: web
    name: emotion-detection-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cp -r backend/src/* .
    startCommand: |
      export PYTHONPATH=/opt/render/project/src
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /
